package storage

import (
	"credo/logger"
	"fmt"
	"os"
	"path/filepath"
)

const defaultContent = `# !!! WARNING !!!
# This file is automatically generated by CREDO.
# CREDO is a tool designed to create reproducible environments.
---
`

type FileStorage struct {
	Filename string
}

func (s *FileStorage) Write(data []byte) {
	content := []byte(defaultContent)
	content = append(content, data...)

	dir := filepath.Dir(s.Filename)
	tmp, err := os.CreateTemp(dir, ".credospell-*.tmp")
	if err != nil {
		logger.Get().Fatal(fmt.Errorf("storage: create temp file: %w", err))
	}
	tmpName := tmp.Name()

	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		logger.Get().Fatal(fmt.Errorf("storage: write temp file: %w", err))
	}
	if err := tmp.Chmod(0600); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		logger.Get().Fatal(fmt.Errorf("storage: chmod temp file: %w", err))
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		logger.Get().Fatal(fmt.Errorf("storage: close temp file: %w", err))
	}
	if err := os.Rename(tmpName, s.Filename); err != nil {
		os.Remove(tmpName)
		logger.Get().Fatal(fmt.Errorf("storage: rename temp file: %w", err))
	}
}

func (s *FileStorage) Read() []byte {
	_, err := os.Stat(s.Filename)
	if os.IsNotExist(err) {
		s.Write([]byte(""))
	}

	data, err := os.ReadFile(s.Filename)
	if err != nil {
		logger.Get().Fatal(err)
	}
	return data
}
