package storage

import (
	"credo/logger"
	"os"
)

const defaultContent = `# !!! WARNING !!!
# This file is automatically generated by CREDO.
# CREDO is a tool designed to create reproducible environments.
---
`

type FileStorage struct {
	Filename string
}

func (s *FileStorage) Write(data []byte) {
	// Checks if file exists
	_, err := os.Stat(s.Filename)
	if os.IsNotExist(err) {
		file, err := os.Create(s.Filename)
		if err != nil {
			logger.Get().Fatal(err)
		}
		_, err = file.WriteString(defaultContent)
		file.Close()
		if err != nil {
			logger.Get().Fatal(err)
		}
	}

	content := []byte(defaultContent)
	content = append(content, data...)

	if err := os.WriteFile(s.Filename, content, 0644); err != nil {
		logger.Get().Fatal(err)
	}
}

func (s *FileStorage) Read() []byte {
	_, err := os.Stat(s.Filename)
	if os.IsNotExist(err) {
		s.Write([]byte(""))
	}

	data, err := os.ReadFile(s.Filename)
	if err != nil {
		logger.Get().Fatal(err)
	}
	return data
}
